name: Build Armbian Image

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false
        default: "main"
      config_file:
        type: string
        required: true
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: "main"
      config_file:
        type: string
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout armbian/build
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          ref: ${{ inputs.ref }}

      - name: Checkout Board Config
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.config_file }}
          sparse-checkout-cone-mode: false

      - name: Parse Config Name
        id: config-name
        run: |
          var=$(basename ${{ inputs.config_file }})
          board=${var#config-}; board=${board%.conf}
          echo "CONFIG_NAME=${board}" >> "$GITHUB_OUTPUT"

      - run: tree .

      - name: Build Armbian Image
        run: ./compile.sh build ${{ steps.config-name.outputs.CONFIG_NAME }}

      - name: Check Output Files
        if: ${{ !cancelled() }}
        run: tree output/

      - name: Upload Build Logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: output-logs
          path: output/logs

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: output-images
          path: output/images/*
